server:
  servlet:
    context-path: /
  port: 0

spring:
  application:
    name: service-user
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}

jwt:
  token:
    secret-key: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}

openapi:
  service:
    title: ${OPENAPI_NAME}
    version: ${OPENAPI_VERSION}
    url: ${OPENAPI_SOURCE}

springdoc:
  api-docs:
    path: ${SPRINGDOC_APIDOCS}
    enabled: true
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI}
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER}:${EUREKA_PORT}/${EUREKA_NAME}
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30