server:
  servlet:
    context-path: /
  port: 9000

spring:
  application:
    name: service-user
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092

jwt:
  token:
    secret-key: chave-teste-dev
    issuer: pulsar-test-auth

openapi:
  service:
    title: service-user doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30


logging:
  level:
    org.springframework.web: DEBUG