CREATE TABLE IF NOT EXISTS T_USERS (
    PK_USER SERIAL PRIMARY KEY,
    CD_USER UUID NOT NULL,
    NM_USER VARCHAR(100) NOT NULL,
    EM_USER VARCHAR(100) UNIQUE NOT NULL,
    PW_USER VARCHAR(255) NOT NULL
);