CREATE TABLE IF NOT EXISTS T_EMPLOYEES (
    PK_EMPLOYEE BIGINT PRIMARY KEY,
    CD_EMPLOYEE UUID NOT NULL,
    PS_EMPLOYEE VARCHAR(100),
    DP_EMPLOYEE VARCHAR(100),
    CONSTRAINT FK_EMPLOYEE_USER FOREIGN KEY (PK_EMPLOYEE) REFERENCES T_USERS(PK_USER) ON DELETE CASCADE
);