CREATE TABLE IF NOT EXISTS T_USERS_ROLES (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES T_USERS(PK_USER) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES T_ROLES(PK_ROLE) ON DELETE CASCADE
);
