CREATE EXTENSION IF NOT EXISTS "pgcrypto";

INSERT INTO T_ROLES (NM_ROLE) VALUES ('ADMIN');
INSERT INTO T_USERS (CD_USER, NM_USER, EM_USER, PW_USER)
VALUES (gen_random_uuid(), 'Administrador Padrão', 'admin@pulsar.com', '$2a$12$GAwztrt4CD64i.BFN6jPGuWXxC4WXzGw6/qdGHGBxTBTJCh1XoS0.');

INSERT INTO T_USERS_ROLES (USER_ID, ROLE_ID)
VALUES (
    (SELECT PK_USER FROM T_USERS WHERE EM_USER = 'admin@pulsar.com'),
    (SELECT PK_ROLE FROM T_ROLES WHERE NM_ROLE = 'ADMIN')
);